version: "3.9"

services:
  java_app:
    container_name: java_app
    build:
      context: ../app-area-curricular-backend
      dockerfile: ./Dockerfile
    image: pee-java_app:1.0.0
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - java_db
    volumes:
      - java_app_data:/path/to/data/in/container

  # frontend:
  #     container_name: area_frontend
  #     build:
  #       context: ../app-area-curricular-frontend
  #     image: app-area_frontend:v1
  #     ports:
  #       - "3000:80"
  #     depends_on:
  #       - java_app

  java_db:
    container_name: java_db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - java_db_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=${PMA_HOST}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - phpmyadmin_data:/sessions
volumes:
  java_app_data:
  java_db_data:
  phpmyadmin_data:
